/**
 * Application env bindings.
 * Runtime shape is generated by `wrangler types` into worker-configuration.d.ts
 * (`Cloudflare.Env` / global `Env`). Secrets may be absent in pure-local mock runs.
 */
export type Env = Cloudflare.Env;
